add language support
pixie-io/docs.px.dev pull request #16
Opened 2021-05-24 15:41 UTC by postescu

2021-05-24 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pixie-labs/pixie-docs?pullRequest=16) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pixie-labs/pixie-docs?pullRequest=16) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pixie-labs/pixie-docs?pullRequest=16) it.</sub>

2021-05-27 19:56 UTC, htroisi commented on src/templates/docs.tsx
> -                Copyright © 2018- The Pixie Authors. All Rights Reserved.
@postescu - could you revert this change to the copyright?

2021-06-03 22:10 UTC, htroisi requested changes
1. Merging in main added new content not under the `en` folder. Could you move `/content/reference/05-plugins` and `/content/tutorials/08-grafana.md` to the `content/en` folder?

2. If English is the only option for the content page, could you explicitly list it in the language drop down menu? (I DM'd you a video).

2021-06-07 16:38 UTC, htroisi commented
@postescu - Could you remove the last commit? That feature is intended for the other docs repo.

2021-06-09 17:01 UTC, htroisi approved these changes

2021-06-09 17:02 UTC, aimichelle approved these changes

2021-06-09 21:02 UTC, merged