Update generated documentation after fixing px.otel and px.export docs
pixie-io/docs.px.dev pull request #189
Opened 2022-06-06 19:16 UTC by philkuz

Signed-off-by: Phillip Kuznetsov <pkuznetsov@pixielabs.ai>

2022-06-06 20:00 UTC, vihangm approved these changes

2022-06-06 20:00 UTC, vihangm requested changes
Can you investigate?
```
12:29:43 PM: failed Building static HTML for pages - 35.084s
12:29:43 PM: error Building static HTML failed for path "/reference/pxl/udf/upid/"
```

2022-06-07 17:32 UTC, vihangm approved these changes

2022-06-07 17:32 UTC, merged

2022-06-16 00:45 UTC, htroisi commented
This is strange: these updates are included in the `prod` branch, but they aren't visible on the website. For example, [this page](https://docs.px.dev/reference/pxl/operators/dataframe.ctx.__getitem__/) still includes `deployment_name`.

2022-06-17 21:18 UTC, htroisi commented
In case this happens again, the fix for this was to log into Netlify, select the latest Production build, then select `Options` --> `clear cache and retry deploy`.